stages:
  data_ingestion:
    cmd: python3 src/yolo5/pipeline/stage_01_data_ingestion.py
    deps:
      - src/yolo5/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion
